config/routes.rb
Framework2::Application.routes.draw do
  resources :groups

  resources :comments

  get "dashboard/index"

  resources :permissions

  resources :media do
    member do
      get 'download_original'
      get 'download_medium'
      get 'download_thumb'
      get 'download_quadratic'
    end
    resources :comments
    resources :tags
  end

  devise_for :users

  resources :users

  resources :roles

  resources :tags

  resources :folders do
    member do
      get 'download_medium'
      get 'download_quadratic'
      get 'download_thumb'
    end
    resources :media do
      member do
        get 'download_original'
        get 'download_medium'
        get 'download_thumb'
        get 'download_quadratic'
      end
      resources :comments
      resources :tags
    end
  end

  root :to => "dashboard#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  has_many :media
  # owner
  belongs_to :user
  # roles that are allowed to access folder
  has_and_belongs_to_many :roles

  has_attached_file :cover,
                    :path => ":rails_root/private/:class/:id/:style/:basename.:extension",
                    :url => "/:class/:id/download_:style",
                    :styles => { :medium => "300x300>", :quadratic => "200x200#", :thumb => "50x50#" }

  validates :name, :description, :cover_file_name, :user_id, :roles, :presence => true
  validates :user_id, :numericality => { :only_integer => true }
  validates :name, :uniqueness => true

  def next
    Folder.where("id > ?", self.id).order("id ASC").first
  end

  def previous
    Folder.where("id < ?", self.id).order("id DESC").first
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

#  before_filter :authenticate_user!
  load_and_authorize_resource

  def download_medium
    @folder = Folder.find(params[:id])
    send_file @folder.cover.path(:medium), :type => @folder.cover_content_type, :disposition => 'inline'
  end

  def download_quadratic
    @folder = Folder.find(params[:id])
    send_file @folder.cover.path(:quadratic), :type => @folder.cover_content_type, :disposition => 'inline'
  end

  def download_thumb
    @folder = Folder.find(params[:id])
    send_file @folder.cover.path(:thumb), :type => @folder.cover_content_type, :disposition => 'inline'
  end

  # GET /folders
  # GET /folders.xml
  def index
    @folders = Folder.accessible_by(current_ability).paginate :page => params[:page], :order => "created_at DESC", :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.xml
  def show
    @folder = Folder.find(params[:id])
    @media = Medium.where("folder_id = ?", params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.xml
  def new
    @folder = Folder.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.xml
  def create
    @folder = Folder.new(params[:folder])

    respond_to do |format|
      if @folder.save
        @users = User.all
        @users.each do |u|
          FolderMailer.notify_new_folder(@folder,u).deliver
        end
        format.html { redirect_to(@folder, :notice => 'Folder was successfully created.') }
        format.xml  { render :xml => @folder, :status => :created, :location => @folder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.xml
  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.html { redirect_to(@folder, :notice => 'Folder was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.xml
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to(folders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder, :html => { :multipart => true }) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :cover %><br />
    <%= f.file_field :cover %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <% for role in Role.find(:all) %>
      <div>
        <%= check_box_tag "folder[role_ids][]", role.id, @folder.roles.include?(role) %>
        <%= role.name %>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<% if can? :create, Folder %>
<div><%= link_to image_tag("add_32x32.png"), new_folder_path %></div>
<% end %>

<div><%= will_paginate @folders %></div>

<div class="table">
<% @folders.each_with_index do |f,i| %>
  <% if i%3 == 0 %>
  <div class="tr">
  <% end %>
    <div class="td cover">
      <div><%= link_to image_tag(f.cover.url(:quadratic)), f %></div>
      <div><%= distance_of_time_in_words(Time.now, f.created_at) %> ago</div>
      <div><%= link_to "#{f.name} (#{f.media.size})", f %></div>
    </div>
  <% if ( i%3 == 2 ) || ( i+1 == @folders.size ) %>
  </div>
  <% end %>
<% end %>
</div>

<div><%= will_paginate @folders %></div>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<div class="table">
  <div class="tr">
    <div class="td">
      <div class="cover float">
        <%= image_tag(@folder.cover.url(:medium)) %>
      </div>
      <div class="foldername left"><%= @folder.name %> <% if can? :update, Folder %>(<%= link_to 'Edit', edit_folder_path(@folder) %>)<% end %> <% if can? :destroy, Folder %>(<%= link_to 'Destroy', @folder, :confirm => 'Are you sure?', :method => :delete %>)<% end %></div>
      <div class="left"><%= @folder.description %></div>
    </div>
  </div>
  <div class="tr">
    <div class="td">
      <div class="table">
        <div class="tr">
          <div class="td left border">
            <% @media.each do |m| %>
            <span class="thumbs"><%= link_to image_tag(m.file.url(:quadratic)), m %></span>
            <% end %>
            <span><% if can? :create, Medium %><%= link_to image_tag("add_48x48.png"), new_folder_medium_path(@folder) %><% end %></span>
          </div>
          <div class="td top border">
            <div class="table">
              <div class="tr">
                <div class="th left">Created by:</div>
                <div class="td left"><%= link_to @folder.user.username, user_path(@folder.user) %></div>
              </div>
              <div class="tr">
                <div class="th left">Tagged with:</div>
                <div class="td left">
                  <% @folder.media.each do |m| %>
                  <%= m.tags.collect(&:name).join(", ") %>
                  <% end %>
                </div>
              </div>
              <div class="tr">
                <div class="th left">Accessible by:</div>
                <div class="td left">
                  <%= @folder.roles.collect(&:name).join(", ") %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>