config/routes.rb
Framework2::Application.routes.draw do
  resources :groups

  resources :comments

  get "dashboard/index"

  resources :permissions

  resources :media do
    member do
      get 'download_original'
      get 'download_medium'
      get 'download_thumb'
      get 'download_quadratic'
    end
    resources :comments
    resources :tags
  end

  devise_for :users

  resources :users

  resources :roles

  resources :tags

  resources :folders do
    member do
      get 'download_medium'
      get 'download_quadratic'
      get 'download_thumb'
    end
    resources :media do
      member do
        get 'download_original'
        get 'download_medium'
        get 'download_thumb'
        get 'download_quadratic'
      end
      resources :comments
      resources :tags
    end
  end

  root :to => "dashboard#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base

  has_many :media
  # owner
  belongs_to :user
  # roles that are allowed to access folder
  has_and_belongs_to_many :roles

  has_attached_file :cover,
                    :path => ":rails_root/private/:class/:id/:style/:basename.:extension",
                    :url => "/:class/:id/download_:style",
                    :styles => { :medium => "300x300>", :quadratic => "200x200#", :thumb => "50x50#" }

  validates :name, :description, :cover_file_name, :user_id, :roles, :presence => true
  validates :user_id, :numericality => { :only_integer => true }
  validates :name, :uniqueness => true

  def next
    Folder.where("id > ?", self.id).order("id ASC").first
  end

  def previous
    Folder.where("id < ?", self.id).order("id DESC").first
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_many :folders
  has_many :comments

  validates :email, :username, :encrypted_password, :presence => true
  validates :email, :username, :uniqueness => true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :role_ids, :roles

  def role?(role)
    #return !!self.roles.find_by_name(role.to_s.camelize)
    return self.roles.find_by_name(role).try(:name) == role.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.xml
  def index
    @users = User.accessible_by(current_ability).paginate :page => params[:page], :order => "email ASC", :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <% for role in Role.where("not name = ?","Public") %>
  <div>
    <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
    <%= role.name %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if can? :create, User %>
<div><%= link_to image_tag("add_32x32.png"), new_user_path %></div>
<% end %>

<div><%= will_paginate @users %></div>

<div class="table">
  <div class="tr">
    <div class="th">Email</div>
    <div class="th">Username</div>
    <div class="th">Roles</div>
    <div class="th"># Folders created</div>
    <div class="th">Last log-in at</div>
    <div class="th"></div>
    <div class="th"></div>
    <div class="th"></div>
  </div>
<% @users.each do |user| %>
  <div class="tr <%= cycle("odd", "even") %>">
    <div class="td"><%= user.email %></div>
    <div class="td"><%= user.username %></div>
    <div class="td"><% user.roles.each do |r| %><%= link_to r.name, role_path(r) %> <% end %></div>
    <div class="td"><%= user.folders.size %></div>
    <div class="td"><% if user.last_sign_in_at.nil? %>-<% else %><%= distance_of_time_in_words(Time.now, user.last_sign_in_at) %><% end %></div>
    <div class="td"><%= link_to 'Show', user %></div>
    <div class="td"><% if can? :update, User %><%= link_to 'Edit', edit_user_path(user) %><% end %></div>
    <div class="td"><% if can? :destroy, User %><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %><% end %></div>
  </div>
<% end %>
</div>

<div><%= will_paginate @users %></div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Roles:</b>
  <%= @user.roles.collect(&:name).join(", ") %>
</p>

<p>
<b>Folders created:</b>
<div>
  <% @user.folders.each do |f| %>
    <span class="thumbs">
      <%= link_to image_tag(f.cover(:thumb)), folder_path(f) %>
    </span>
  <% end %>
</div>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>