config/routes.rb
Framework2::Application.routes.draw do
  resources :groups

  resources :comments

  get "dashboard/index"

  resources :permissions

  resources :media do
    member do
      get 'download_original'
      get 'download_medium'
      get 'download_thumb'
      get 'download_quadratic'
    end
    resources :comments
    resources :tags
  end

  devise_for :users

  resources :users

  resources :roles

  resources :tags

  resources :folders do
    member do
      get 'download_medium'
      get 'download_quadratic'
      get 'download_thumb'
    end
    resources :media do
      member do
        get 'download_original'
        get 'download_medium'
        get 'download_thumb'
        get 'download_quadratic'
      end
      resources :comments
      resources :tags
    end
  end

  root :to => "dashboard#index"

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  belongs_to :folder
  has_and_belongs_to_many :tags
  has_many :comments

  has_attached_file :file,
                    :path => ":rails_root/private/:class/:id/:style/:basename.:extension",
                    :url => "/:class/:id/download_:style",
                    :styles => { :medium => "300x300>", :thumb => "100x100>", :quadratic => "50x50#" }

  validates :file_file_name, :folder_id, :presence => true
  validates :folder_id, :numericality => { :only_integer => true }

  def next
    Medium.where("id > ? and folder_id = ?", self.id, self.folder.id).order("id ASC").first
  end

  def previous
    Medium.where("id < ? and folder_id = ?", self.id, self.folder.id).order("id DESC").first
  end

  def up
    Folder.where("id = ?", self.folder.id).first
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController

#  before_filter :authenticate_user!
  load_and_authorize_resource

  def download_original
    @medium = Medium.find(params[:id])
    send_file @medium.file.path, :type => @medium.file_content_type, :disposition => 'inline'
  end

  def download_medium
    @medium = Medium.find(params[:id])
    send_file @medium.file.path(:medium), :type => @medium.file_content_type, :disposition => 'inline'
  end

  def download_thumb
    @medium = Medium.find(params[:id])
    send_file @medium.file.path(:thumb), :type => @medium.file_content_type, :disposition => 'inline'
  end

  def download_quadratic
    @medium = Medium.find(params[:id])
    send_file @medium.file.path(:quadratic), :type => @medium.file_content_type, :disposition => 'inline'
  end

  # GET /media
  # GET /media.xml
  def index
    @media = Medium.accessible_by(current_ability).paginate :page => params[:page], :order => "created_at DESC", :per_page => 10
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @media }
    end
  end

  # GET /media/1
  # GET /media/1.xml
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/new
  # GET /media/new.xml
  def new
    @medium = Medium.new
    @tags = Tag.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
    @tags = Tag.all
  end

  # POST /media
  # POST /media.xml
  def create
    @medium = Medium.new(params[:medium])
    @medium.tags = Tag.find(params[:tag_ids]) if params[:tag_ids]

    respond_to do |format|
      if @medium.save
        format.html { redirect_to(@medium.folder, :notice => 'Medium was successfully created.') }
        format.xml  { render :xml => @medium.folder, :status => :created, :location => @medium }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @medium.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.xml
  def update
    @medium = Medium.find(params[:id])
    @medium.tags = Tag.find(params[:tag_ids]) if params[:tag_ids]

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to(@medium, :notice => 'Medium was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @medium.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.xml
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to(media_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.erb
<%= form_for(@medium, :html => { :multipart => true }) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.hidden_field :folder_id, :value => params[:folder_id] %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <% for tag in @tags %>
    <input type="checkbox" id="<%= tag.id %>" name="tag_ids[]" value="<%= tag.id %>" <% if @medium.tags.include? tag %>checked="checked"<% end %>/> <%= tag.name %><br/>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<div><%= will_paginate @media %></div>

<div class="table">
  <div class="tr">
    <div class="th">File</div>
    <div class="th">Folder</div>
    <div class="th"># Tags</div>
    <div class="th"># Comments</div>
    <div class="th"># Roles that can access Medium</div>
    <div class="th">Created at</div>
    <div class="th"></div>
    <div class="th"></div>
  </div>
<% @media.each do |medium| %>
  <div class="tr <%= cycle('odd', 'even') %>">
    <div class="td thumbs"><%= link_to image_tag(medium.file.url(:thumb)), medium %></div>
    <div class="td"><%= link_to medium.folder.name, folder_path(medium.folder) %></div>
    <div class="td"><%= medium.tags.size %></div>
    <div class="td"><%= medium.comments.size %></div>
    <div class="td"><%= medium.folder.roles.size %></div>
    <div class="td"><%= distance_of_time_in_words(Time.now, medium.created_at) %></div>
    <div class="td"><%= link_to 'Edit', edit_medium_path(medium) %></div>
    <div class="td"><%= link_to 'Destroy', medium, :confirm => 'Are you sure?', :method => :delete %></div>
  </div>
<% end %>
</div>

<div><%= will_paginate @media %></div>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<div class="table">
  <div class="tr">
    <div class="td">
      <%= link_to image_tag("previous_48x48.png"), medium_path(@medium.previous) %>
    </div>
    <div class="td cover">
      <%= link_to (image_tag @medium.file.url(:medium)), @medium.file.url(:original) %>
    </div>
    <div class="td">
      <%= link_to image_tag("next_48x48.png"), medium_path(@medium.next) %>
    </div>
  </div>
</div>
<div class="table">
  <div class="tr">
    <div class="td">
      <div class="table">
        <div class="tr">
          <div class="td border top">
            <div class="table">
              <div class="tr">
                <div class="td left">
                  <% if can? :create, Comment %>
                    <%= link_to "Add comment", new_medium_comment_path(@medium) %>
                  <% end %>
                </div>
                <div class="td">
                </div>
              </div>
              <% @medium.comments.order("created_at DESC").each do |c| %>
                <div class="tr <%= cycle("odd", "even") %>">
                <div class="td top left">
                  <%= c.user.username %>:
                </div>
                <div class="td top left">
                  "<%= c.text %>"
                </div>
              </div>
            <% end %>
            </div>
          </div>
          <div class="td border top">
            <div class="table">
              <div class="tr">
                <div class="th left"></div>
                <div class="td left"><% if can? :update, Medium %><%= link_to "Edit", edit_medium_path(@medium) %><% end %></div>
              </div>
              <div class="tr">
                <div class="th left">Created by:</div>
                <div class="td left"><%= @medium.folder.user.username %></div>
              </div>
              <div class="tr">
                <div class="th left">Tagged with:</div>
                <div class="td left"><%= @medium.tags.collect(&:name).join(", ") %></div>
              </div>
              <div class="tr">
                <div class="th left">Accessible by:</div>
                <div class="td left"><%= @medium.folder.roles.collect(&:name).join(", ") %></div>
              </div>
              <div class="tr">
                <div class="th left">in Folder:</div>
                <div class="td left thumbs"><%= link_to (image_tag @medium.folder.cover.url(:thumb)), @medium.folder, :title => @medium.folder.name %></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
<div class="table hover">
  <div class="tr">
    <div class="td cover float">
      <%= link_to (image_tag @medium.file.url(:medium)), @medium.file.url(:original) %>
    </div>
  </div>
  <div class="tr">
    <div class="td">
<div class="table hide">
  <div class="tr">
    <div class="td right">
      <b>Folder:</b>
    </div>
    <div class="td">
      <%= image_tag @medium.folder.cover.url(:thumb) %><br/>
      <%= @medium.folder.name %>
    </div>
    <div class="td right">
      <b>Roles:</b>
    </div>
    <div class="td">
      <%= @medium.folder.roles.collect(&:name).join(", ") %>
    </div>
    <div class="td right">
      <b>Tags:</b>
    </div>
    <div class="td">
      <%= @medium.tags.collect(&:name).join(", ") %>
    </div>
  </div>
</div>
<div class="table hide">
  <div class="tr">
    <div class="td">
      <%= link_to "Add comment", new_medium_comment_path(@medium) %>
    </div>
    <div class="td">
    </div>
    <div class="td">
    </div>
  </div>
  <% @medium.comments.order("created_at DESC").each do |c| %>
    <div class="tr">
      <div class="td">
        On <%= c.created_at.to_formatted_s(:short) %>
      </div>
      <div class="td">
        <%= c.user.username %> said:
      </div>
      <div class="td">
        "<%= c.text %>"
      </div>
    </div>
  <% end %>
  </div>
</div>
</div>
</div>
</div>
<div class="actions">
  <%= link_to image_tag("previous_48x48.png"), medium_path(@medium.previous) %>
  <%= link_to image_tag("up_48x48.png"), folder_path(@medium.up) %>
  <%= link_to image_tag("next_48x48.png"), medium_path(@medium.next) %>
  <%= link_to 'Edit', edit_medium_path(@medium) %>
</div>
-->