config/routes.rb
Framework2::Application.routes.draw do
  resources :groups

  resources :comments

  get "dashboard/index"

  resources :permissions

  resources :media do
    member do
      get 'download_original'
      get 'download_medium'
      get 'download_thumb'
      get 'download_quadratic'
    end
    resources :comments
    resources :tags
  end

  devise_for :users

  resources :users

  resources :roles

  resources :tags

  resources :folders do
    member do
      get 'download_medium'
      get 'download_quadratic'
      get 'download_thumb'
    end
    resources :media do
      member do
        get 'download_original'
        get 'download_medium'
        get 'download_thumb'
        get 'download_quadratic'
      end
      resources :comments
      resources :tags
    end
  end

  root :to => "dashboard#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Framework2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class="menu borders">
    <div class="table">
      <div class="tr">
        <div class="td"><%= link_to image_tag("home_32x32.png"), root_path %></div>
        <div class="td"><% if can? :read_all, Folder %><%= link_to 'folders', folders_path %><% end %></div>
        <div class="td"><% if can? :read, Tag %><%= link_to 'tags', tags_path %><% end %></div>
        <div class="td"><% if can? :read_all, Medium %><%= link_to 'media', media_path %><% end %></div>
        <div class="td"><% if can? :read, Comment %><%= link_to 'comments', comments_path %><% end %></div>
        <div class="td"><% if can? :read, User %><%= link_to 'users', users_path %><% end %></div>
        <div class="td"><% if can? :read, Role %><%= link_to 'roles', roles_path %><% end %></div>
        <div class="td"><%= render 'devise/menu/login_items' %></div>
      </div>
    </div>
  </div>

  <% if notice || alert %>
  <div class="info borders">
    <% if notice %>
    <div>
      <%= image_tag "info_32x32.png" %>
      <%= notice %>
    </div>
    <% elsif alert %>
    <div>
      <%= image_tag "error_32x32.png" %>
      <%= alert %>
    </div>
    <% end %>
  </div>
  <% end %>

  <div class="content borders">
    <%= yield %>
  </div>

</body>
</html>